name: Contract Security

permissions:
  contents: write
  security-events: write
  actions: write

on:
  push:
    branches: [ main, 'devin/*' ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network: [ethereum, polygon, arbitrum, optimism, avalanche, bsc, base, gnosis, fantom, metis]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Slither
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.3'
          
      - uses: pnpm/action-setup@v2
        with:
          version: 10.3.0
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Run Slither
        run: slither . --json slither-report.json || true
        
      - name: Check Contract Size
        run: pnpm hardhat size-contracts
        
      - name: Upload Slither Report
        uses: actions/upload-artifact@v3
        with:
          name: slither-report
          path: slither-report.json
